[project]
name = "crm"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "django>=6.0",
    "django-admin-charts>=1.5.0",
    "django-filter>=25.2",
    "django-jazzmin>=3.0.1",
    "psycopg2-binary>=2.9.11",
    "python-dotenv>=1.2.1",
]
